### ISSUE TITLE
mailUtils 在哪里定义的？

### ISSUE THREAD

**Issue by changhaonan** [paramiao/pyMail#6]

**Comment by yuzhou03** [comment]
同问  example都运行不起来 有点太差劲了吧

**Comment by raymondlu31** [comment]
change "mailUtils" to "pyMail" ......
Please keep consistency.

**Comment by hk8090150** [comment]
我的系统是win7的        折腾了好久    都没找到这个包

**Comment by hk8090150** [comment]
74 1175 1176 1177 1178 1179 1180 1181 1182 1183 1184'])
None

None
('', '')
('', '')
None
#遍历未读邮件 都是空的。。是不是  我获取的方法有错误呀
